doveobj = [
    {"words": [{"word": "Sumuga-duwa","morphemes": "sumu-ga-duwa", "gloss": "once-MOD-also", "notes": "..."}, {"word": "soo","morphemes": "soo", "gloss": "NOM", "notes": "..."}, {"word": "ehobe","morphemes": "ehobe", "gloss": "dove", "notes": "..."}, {"word": "wahoo-ga","morphemes": "wahoo-ga", "gloss": "two.ACC-have", "notes": "..."}, {"word": "tooamutse’e-gana","morphemes": "tooa-mu-tse’e-gana", "gloss": "child-PL-DIM-have", "notes": "..."}, {"punctuation": "."}, {"punctuation": "”"}], "translation": "Once, there was a Dove who had two little children."},
{"words": [{"word": "Umudooga","morphemes": "umu-dooga", "gloss": "they-??", "notes": "..."}, {"word": "tugamane","morphemes": "tuga-mane", "gloss": "eat-do", "notes": "..."}, {"word": "meabodote","morphemes": "mea-bodote", "gloss": "go-round.trip", "notes": "..."}, {"punctuation": "."}], "translation": "She often went out and returned with food for them"},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"word": "sumu","morphemes": "sumu", "gloss": "one", "notes": "..."}, {"word": "tabeno-ga","morphemes": "tabeno-ga", "gloss": "day-MOD", "notes": "..."}, {"punctuation": ","}, {"word": "tu","morphemes": "tu", "gloss": "own", "notes": "..."}, {"word": "dooamu","morphemes": "dooamu", "gloss": "children", "notes": "..."}, {"word": "tu","morphemes": "tu", "gloss": "own", "notes": "..."}, {"word": "nobekwaesoo-ga","morphemes": "nobe-kwae-soo-ga", "gloss": "house-LOC-ADV-MOD", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "3PL", "notes": "..."}, {"word": "tamakwuse","morphemes": "tamakwu-se", "gloss": "leave-SEQ", "notes": "..."}, {"word": "tukamea","morphemes": "tuka-mea", "gloss": "eat-go", "notes": "..."}, {"punctuation": "."}], "translation": "Then one day, apparently, she left her children in her house to go get food."},
{"words": [{"word": "Yise-ga","morphemes": "yise-ga", "gloss": "then-MOD", "notes": "..."}, {"word": "koo","morphemes": "koo", "gloss": "OBL", "notes": "..."}, {"word": "ehobe","morphemes": "ehobe", "gloss": "dove", "notes": "..."}, {"word": "mease","morphemes": "mea-se", "gloss": "go-SEQ", "notes": "..."}, {"punctuation": ","}, {"word": "soo","morphemes": "soo", "gloss": "NOM", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "3PL", "notes": "..."}, {"word": "dooake’e","morphemes": "dooake’e", "gloss": "girls", "notes": "..."}, {"word": "hi’e","morphemes": "hi’e", "gloss": "PAT.uncle", "notes": "..."}, {"word": "ga","morphemes": "ga", "gloss": "?", "notes": "..."}, {"word": "umuba","morphemes": "umu-ba", "gloss": "they-with", "notes": "..."}, {"word": "petuse","morphemes": "petu-se", "gloss": "arrive-SEQ", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "they", "notes": "..."}, {"word": "tubenga","morphemes": "tubenga", "gloss": "ask", "notes": "..."}, {"punctuation": ","}], "translation": "Then after the Dove left, the girls’ paternal uncle arrived to them and asked,"},
{"words": [{"punctuation": "“"}, {"word": "Hanosoo","morphemes": "hanosoo", "gloss": "where", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "you.PL", "notes": "..."}, {"word": "bea","morphemes": "bea", "gloss": "mother", "notes": "..."}, {"word": "meapu","morphemes": "mea-pu", "gloss": "go-PFV", "notes": "..."}, {"punctuation": ","}, {"punctuation": "”"}, {"word": "me’ega","morphemes": "me’e-ga", "gloss": "QTE-MOD", "notes": "..."}, {"punctuation": "."}], "translation": "“Where did your mother go?”"},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"punctuation": ","}, {"punctuation": "“"}, {"word": "me","morphemes": "me", "gloss": "our.EXCL", "notes": "..."}, {"word": "bea","morphemes": "bea", "gloss": "mother", "notes": "..."}, {"word": "tugameapu","morphemes": "tuga-mea-pu", "gloss": "eat-go-PFV", "notes": "..."}, {"punctuation": ","}, {"punctuation": "”"}, {"word": "me’e","morphemes": "me’e", "gloss": "QTE", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "3PL", "notes": "..."}, {"word": "tooake’e","morphemes": "tooake’e", "gloss": "girls", "notes": "..."}, {"punctuation": "."}], "translation": "Then, “Our mother went to get food,” the girls said."},
{"words": [{"word": "Soo","morphemes": "soo", "gloss": "NOM", "notes": "..."}, {"word": "hi’e","morphemes": "hi’e", "gloss": "PAT.uncle", "notes": "..."}, {"word": "yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "them", "notes": "..."}, {"word": "nekuseka","morphemes": "nekuseka", "gloss": "scold", "notes": "..."}], "translation": "The paternal uncle scolded them,"},
{"words": [{"punctuation": "“"}, {"word": "Tuwaga-duwasoo","morphemes": "tuwaga-duwasoo", "gloss": "hole-also", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "you.PL", "notes": "..."}, {"word": "bea-ga","morphemes": "bea-ga", "gloss": "mother-MOD", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "3PL", "notes": "..."}, {"word": "tu","morphemes": "tu", "gloss": "own", "notes": "..."}, {"word": "pubua’a","morphemes": "pu-bua’a", "gloss": "RE~friend", "notes": "..."}, {"punctuation": ","}, {"punctuation": "”"}], "translation": "“Your mother goes to the hole/stock-pile(?) of her friends;”"},
{"words": [{"punctuation": "“"}, {"word": "hema","morphemes": "hema", "gloss": "what", "notes": "..."}, {"word": "how","morphemes": "how", "gloss": "how", "notes": "..."}, {"word": "tugwekwaetuga","morphemes": "tugwekwaetuga", "gloss": "?????????", "notes": "..."}, {"word": "hane’yaina","morphemes": "hane-’yai-na", "gloss": "do-HAB-SIM", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "2PL", "notes": "..."}, {"word": "tukakute","morphemes": "tuka-kute", "gloss": "eat-APL", "notes": "..."}, {"punctuation": ","}, {"punctuation": "”"}, {"word": "me’ega","morphemes": "me’e-ga", "gloss": "QTE-MOD", "notes": "..."}, {"word": "yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"word": "soo","morphemes": "soo", "gloss": "NOM", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "3PL", "notes": "..."}, {"word": "hi’e","morphemes": "hi’e", "gloss": "PAT.uncle", "notes": "..."}, {"punctuation": "."}], "translation": "“that’s what she does to bring you food to eat,” their uncle said."},
{"words": [{"word": "Mu","morphemes": "mu", "gloss": "3PL", "notes": "..."}, {"word": "netammase","morphemes": "netamma-se", "gloss": "tell-SEQ", "notes": "..."}, {"punctuation": ","}, {"word": "umuba’yoo","morphemes": "umu-ba’yoo", "gloss": "they-from.with", "notes": "..."}, {"word": "me","morphemes": "me", "gloss": "QTE", "notes": "..."}, {"word": "mea","morphemes": "mea", "gloss": "go", "notes": "..."}, {"punctuation": ","}, {"word": "yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"word": "umu","morphemes": "umu", "gloss": "they", "notes": "..."}, {"word": "tooake’e","morphemes": "tooake’e", "gloss": "girls", "notes": "..."}, {"word": "suda","morphemes": "suda", "gloss": "bad", "notes": "..."}, {"word": "nuumase","morphemes": "nuuma-se", "gloss": "feel-SEQ", "notes": "..."}, {"word": "oe","morphemes": "oe", "gloss": "there", "notes": "..."}, {"word": "kono’o","morphemes": "kono’o", "gloss": "stand.PL", "notes": "..."}, {"punctuation": "."}], "translation": "After telling them, it’s said he went away from them, and then the girls were sad standing there."},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"word": "umu","morphemes": "umu", "gloss": "they", "notes": "..."}, {"word": "tooake’e","morphemes": "tooake’e", "gloss": "girls", "notes": "..."}, {"word": "pea","morphemes": "pea", "gloss": "mother", "notes": "..."}, {"word": "yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"word": "petu","morphemes": "petu", "gloss": "arrive", "notes": "..."}, {"punctuation": ""}], "translation": "Then the girls’ mother arrived."},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"word": "umu","morphemes": "umu", "gloss": "they", "notes": "..."}, {"word": "tooake’e","morphemes": "tooake’e", "gloss": "girls", "notes": "..."}, {"word": "tu","morphemes": "tu", "gloss": "own", "notes": "..."}, {"word": "pea","morphemes": "pea", "gloss": "mother", "notes": "..."}, {"word": "tuukwe’e","morphemes": "tuukwe’e", "gloss": "tell", "notes": "..."}], "translation": "Then the girls told their mother,"},
{"words": [{"punctuation": "“"}, {"word": "Me","morphemes": "me", "gloss": "our", "notes": "..."}, {"word": "bea","morphemes": "bea", "gloss": "mother", "notes": "..."}, {"word": "u","morphemes": "u", "gloss": "you", "notes": "..."}, {"punctuation": ","}, {"word": "soo","morphemes": "soo", "gloss": "NOM", "notes": "..."}, {"word": "me","morphemes": "me", "gloss": "our", "notes": "..."}, {"word": "hi’e","morphemes": "hi’e", "gloss": "uncle", "notes": "..."}, {"word": "nummeba","morphemes": "numme-ba", "gloss": "us-with", "notes": "..."}, {"word": "petuse","morphemes": "petu-se", "gloss": "arrive-SEQ", "notes": "..."}, {"punctuation": ","}, {"word": "me","morphemes": "me", "gloss": "us", "notes": "..."}, {"word": "nekuseka","morphemes": "nekuseka", "gloss": "scold", "notes": "..."}, {"punctuation": ","}, {"punctuation": "”"}, {"word": "me’e","morphemes": "me’e", "gloss": "QTE", "notes": "..."}, {"word": "tu","morphemes": "tu", "gloss": "own", "notes": "..."}, {"word": "pea","morphemes": "pea", "gloss": "mother", "notes": "..."}, {"word": "tuukwe’e","morphemes": "tuukwe’e", "gloss": "tell", "notes": "..."}, {"punctuation": "."}], "translation": "“Our mother! Our paternal uncle came and scolded us,” so they told their mother."},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"word": "soo","morphemes": "soo", "gloss": "NOM", "notes": "..."}, {"word": "mu","morphemes": "mu", "gloss": "3PL", "notes": "..."}, {"word": "bea","morphemes": "bea", "gloss": "mother", "notes": "..."}, {"word": "suda","morphemes": "suda", "gloss": "bad", "notes": "..."}, {"word": "nuumase","morphemes": "nuuma-se", "gloss": "feel-SEQ", "notes": "..."}, {"punctuation": ","}], "translation": "Then their mother felt bad,"},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"word": "yagakooha","morphemes": "yaga-kooha", "gloss": "cry-begin", "notes": "..."}, {"punctuation": ","}, {"word": "‘Hoowehoho","morphemes": "hoowehoho", "gloss": "hoowehoho", "notes": "..."}, {"punctuation": ","}, {"word": "Hoowehoho","morphemes": "hoowehoho", "gloss": "hoowehoho", "notes": "..."}, {"word": "ho","morphemes": "ho", "gloss": "ho", "notes": "..."}, {"punctuation": ","}, {"punctuation": "”"}, {"word": "me’e","morphemes": "me’e", "gloss": "QTE", "notes": "..."}, {"word": "yise","morphemes": "yise", "gloss": "then", "notes": "..."}, {"punctuation": "."}], "translation": "And she began to cry, ‘Hoowehoho, Hoowehoho ho.”"}
]
add = [
    "Sümüga-düwa su ihobi wahu-ga tuamütsi’i-gana",
    "Ümüduga tügamani miabodoti",
    "Yeiši šümü tabino-ga tü duamü tü nobikweišu-ga mü tamakwusi tukamia",
    "Yeiši-ga ku ihobi miasi šu mü tuaki’i hai’i ga ümüma pitüsi mü tübinga",
    "Hanosu mü bia miapü mi’iga",
    "Yeiši mi bia tügamiapü mi’i mü duaki’i",
    "Su hai’i yeiši mü niküsika",
    "Tüwaga-düwasu mü bia-ga mü tü pübüa’a",
    "hima hau tügwikweitüga hani’yaina mü tükaküti mi’iga yeiši šu mü hai’i",
    "Mü nitammasi ümüba’yu mi mia yeiši ümü tuaki’i šüda nüümasi oi kono’o",
    "Yeiši ümü tuaki’i pia yeiši pitü",
    "Yeiši ümü tuaki’i tü pia tüüki’i",
    "Mi bia ü su mi hai’i nümmiba pitüsi mi niküsika mi’i tü pia tüükwi’i",
    "Yeiši su mü pia süda nüümasi",
    "Yeiši yagakooha Huwihoho Huwihoho ho mi’i yeiši"
]
sentNumber = -1
for item in add:
    wordNumber=-1
    sentNumber += 1
    sentence = doveobj[sentNumber]["words"]
    words = item.split()
    for sword in words:
        wordNumber += 1
        match = False
        while not match:
            try:
                sentence[wordNumber]["word"]
                sentence[wordNumber]["variant-ortho"] = sword
                match = True
            except IndexError:
                match = True
            except:
                wordNumber += 1
                match = False

print(doveobj)


