import requests
import sys


obj = [
    {"words": [{"word": "Sumuga-duwa","morphemes": "sumu-ga-duwa", "gloss": "once-MOD-also"}, {"word": "soo","morphemes": "soo", "gloss": "NOM"}, {"word": "ehobe","morphemes": "ehobe", "gloss": "dove"}, {"word": "wahoo-ga","morphemes": "wahoo-ga", "gloss": "two.ACC-have"}, {"word": "tooamutse’e-gana.","morphemes": "tooa-mu-tse’e-gana", "gloss": "child-PL-DIM-have"}], "translation": "Once, there was a Dove who had two little children."},
{"words": [{"word": "Umudooga","morphemes": "umu-dooga", "gloss": "they-??"}, {"word": "tugamane","morphemes": "tuga-mane", "gloss": "eat-do"}, {"word": "meabodote.","morphemes": "mea-bodote", "gloss": "go-round.trip"}], "translation": "She often went out and returned with food for them"},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then"}, {"word": "sumu","morphemes": "sumu", "gloss": "one"}, {"word": "tabeno-ga,","morphemes": "tabeno-ga", "gloss": "day-MOD"}, {"word": "tu","morphemes": "tu", "gloss": "own"}, {"word": "dooamu","morphemes": "dooamu", "gloss": "children"}, {"word": "tu","morphemes": "tu", "gloss": "own"}, {"word": "nobekwaesoo-ga","morphemes": "nobe-kwae-soo-ga", "gloss": "house-LOC-ADV-MOD"}, {"word": "mu","morphemes": "mu", "gloss": "3PL"}, {"word": "tamakwuse","morphemes": "tamakwu-se", "gloss": "leave-SEQ"}, {"word": "tukamea.","morphemes": "tuka-mea", "gloss": "eat-go"}], "translation": "Then one day, apparently, she left her children in her house to go get food."},
{"words": [{"word": "Yise-ga","morphemes": "yise-ga", "gloss": "then-MOD"}, {"word": "koo","morphemes": "koo", "gloss": "OBL"}, {"word": "ehobe","morphemes": "ehobe", "gloss": "dove"}, {"word": "mease,","morphemes": "mea-se", "gloss": "go-SEQ"}, {"word": "soo","morphemes": "soo", "gloss": "NOM"}, {"word": "mu","morphemes": "mu", "gloss": "3PL"}, {"word": "dooake’e","morphemes": "dooake’e", "gloss": "girls"}, {"word": "hi’e","morphemes": "hi’e", "gloss": "PAT.uncle"}, {"word": "ga","morphemes": "ga", "gloss": "?"}, {"word": "umuba","morphemes": "umu-ba", "gloss": "they-with"}, {"word": "petuse","morphemes": "petu-se", "gloss": "arrive-SEQ"}, {"word": "mu","morphemes": "mu", "gloss": "they"}, {"word": "tubenga,","morphemes": "tubenga", "gloss": "ask"}], "translation": "Then after the Dove left, the girls’ paternal uncle arrived to them and asked,"},
{"words": [{"word": "“Hanosoo","morphemes": "hanosoo", "gloss": "where"}, {"word": "mu","morphemes": "mu", "gloss": "you.PL"}, {"word": "bea","morphemes": "bea", "gloss": "mother"}, {"word": "meapu,”","morphemes": "mea-pu", "gloss": "go-PFV"}, {"word": "me’ega.","morphemes": "me’e-ga", "gloss": "QTE-MOD"}], "translation": "“Where did your mother go?”"},
{"words": [{"word": "Yise,","morphemes": "yise", "gloss": "then"}, {"word": "“me","morphemes": "me", "gloss": "our.EXCL"}, {"word": "bea","morphemes": "bea", "gloss": "mother"}, {"word": "tugameapu,”","morphemes": "tuga-mea-pu", "gloss": "eat-go-PFV"}, {"word": "me’e","morphemes": "me’e", "gloss": "QTE"}, {"word": "mu","morphemes": "mu", "gloss": "3PL"}, {"word": "tooake’e.","morphemes": "tooake’e", "gloss": "girls"}], "translation": "Then, “Our mother went to get food,” the girls said."},
{"words": [{"word": "Soo","morphemes": "soo", "gloss": "NOM"}, {"word": "hi’e","morphemes": "hi’e", "gloss": "PAT.uncle"}, {"word": "yise","morphemes": "yise", "gloss": "then"}, {"word": "mu","morphemes": "mu", "gloss": "them"}, {"word": "nekuseka","morphemes": "nekuseka", "gloss": "scold"}], "translation": "The paternal uncle scolded them,"},
{"words": [{"word": "“Tuwaga-duwasoo","morphemes": "tuwaga-duwasoo", "gloss": "hole-also"}, {"word": "mu","morphemes": "mu", "gloss": "you.PL"}, {"word": "bea-ga","morphemes": "bea-ga", "gloss": "mother-MOD"}, {"word": "mu","morphemes": "mu", "gloss": "3PL"}, {"word": "tu","morphemes": "tu", "gloss": "own"}, {"word": "pubua’a,”","morphemes": "pu-bua’a", "gloss": "RE~friend"}], "translation": "“Your mother goes to the hole/stock-pile(?) of her friends;”"},
{"words": [{"word": "“hema","morphemes": "hema", "gloss": "what"}, {"word": "how","morphemes": "how", "gloss": "how"}, {"word": "tugwekwaetuga","morphemes": "tugwekwaetuga", "gloss": "?????????"}, {"word": "hane’yaina","morphemes": "hane-’yai-na", "gloss": "do-HAB-SIM"}, {"word": "mu","morphemes": "mu", "gloss": "2PL"}, {"word": "tukakute,”","morphemes": "tuka-kute", "gloss": "eat-APL"}, {"word": "me’ega","morphemes": "me’e-ga", "gloss": "QTE-MOD"}, {"word": "yise","morphemes": "yise", "gloss": "then"}, {"word": "soo","morphemes": "soo", "gloss": "NOM"}, {"word": "mu","morphemes": "mu", "gloss": "3PL"}, {"word": "hi’e.","morphemes": "hi’e", "gloss": "PAT.uncle"}], "translation": "“that’s what she does to bring you food to eat,” their uncle said."},
{"words": [{"word": "Mu","morphemes": "mu", "gloss": "3PL"}, {"word": "netammase,","morphemes": "netamma-se", "gloss": "tell-SEQ"}, {"word": "umuba’yoo","morphemes": "umu-ba’yoo", "gloss": "they-from.with"}, {"word": "me","morphemes": "me", "gloss": "QTE"}, {"word": "mea,","morphemes": "mea", "gloss": "go"}, {"word": "yise","morphemes": "yise", "gloss": "then"}, {"word": "umu","morphemes": "umu", "gloss": "they"}, {"word": "tooake’e","morphemes": "tooake’e", "gloss": "girls"}, {"word": "suda","morphemes": "suda", "gloss": "bad"}, {"word": "nuumase","morphemes": "nuuma-se", "gloss": "feel-SEQ"}, {"word": "oe","morphemes": "oe", "gloss": "there"}, {"word": "kono’o.","morphemes": "kono’o", "gloss": "stand.PL"}], "translation": "After telling them, it’s said he went away from them, and then the girls were sad standing there."},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then"}, {"word": "umu","morphemes": "umu", "gloss": "they"}, {"word": "tooake’e","morphemes": "tooake’e", "gloss": "girls"}, {"word": "pea","morphemes": "pea", "gloss": "mother"}, {"word": "yise","morphemes": "yise", "gloss": "then"}, {"word": "petu.","morphemes": "petu", "gloss": "arrive"}], "translation": "Then the girls’ mother arrived."},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then"}, {"word": "umu","morphemes": "umu", "gloss": "they"}, {"word": "tooake’e","morphemes": "tooake’e", "gloss": "girls"}, {"word": "tu","morphemes": "tu", "gloss": "own"}, {"word": "pea","morphemes": "pea", "gloss": "mother"}, {"word": "tuukwe’e","morphemes": "tuukwe’e", "gloss": "tell"}], "translation": "Then the girls told their mother,"},
{"words": [{"word": "“Me","morphemes": "me", "gloss": "our"}, {"word": "bea","morphemes": "bea", "gloss": "mother"}, {"word": "u,","morphemes": "u", "gloss": "you"}, {"word": "soo","morphemes": "soo", "gloss": "NOM"}, {"word": "me","morphemes": "me", "gloss": "our"}, {"word": "hi’e","morphemes": "hi’e", "gloss": "uncle"}, {"word": "nummeba","morphemes": "numme-ba", "gloss": "us-with"}, {"word": "petuse,","morphemes": "petu-se", "gloss": "arrive-SEQ"}, {"word": "me","morphemes": "me", "gloss": "us"}, {"word": "nekuseka,”","morphemes": "nekuseka", "gloss": "scold"}, {"word": "me’e","morphemes": "me’e", "gloss": "QTE"}, {"word": "tu","morphemes": "tu", "gloss": "own"}, {"word": "pea","morphemes": "pea", "gloss": "mother"}, {"word": "tuukwe’e.","morphemes": "tuukwe’e", "gloss": "tell"}], "translation": "“Our mother! Our paternal uncle came and scolded us,” so they told their mother."},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then"}, {"word": "soo","morphemes": "soo", "gloss": "NOM"}, {"word": "mu","morphemes": "mu", "gloss": "3PL"}, {"word": "bea","morphemes": "bea", "gloss": "mother"}, {"word": "suda","morphemes": "suda", "gloss": "bad"}, {"word": "nuumase,","morphemes": "nuuma-se", "gloss": "feel-SEQ"}], "translation": "Then their mother felt bad,"},
{"words": [{"word": "Yise","morphemes": "yise", "gloss": "then"}, {"word": "yagakooha,","morphemes": "yaga-kooha", "gloss": "cry-begin"}, {"word": "‘Hoowehoho,","morphemes": "hoowehoho", "gloss": "hoowehoho"}, {"word": "Hoowehoho","morphemes": "hoowehoho", "gloss": "hoowehoho"}, {"word": "ho,’","morphemes": "ho", "gloss": "ho"}, {"word": "me’e","morphemes": "me’e", "gloss": "QTE"}, {"word": "yise.","morphemes": "yise", "gloss": "then"}], "translation": "And she began to cry, ‘Hoowehoho, Hoowehoho ho.”"}
]

send = {
    'author': 'satchez',
    'data': obj
    }
    
requests.put("http://localhost:5001/numu-know/us-central1/app/api/update/1", json=send)